sudo: required
dist: trusty
cache: apt
language: cpp
addons:
  apt:
    packages:
      - fakeroot
      - help2man
      - lintian
      - cppcheck
      - tree
      - debhelper
      - libudev-dev
      - imagemagick
      - qt5-default
      - libqt5serialport5-dev
matrix:
  fast_finish: true

  include:
  - os: osx
    compiler: clang
    env:
        PLATFORM=osx
        PATH=/Users/travis/local/bin:$PATH
        PYTHONPATH=$PYTHONPATH:$HOME/local/lib/python2.7/site-packages 

  - os: linux
    compiler: g++
    env:
        PLATFORM=linux
        PATH=/home/travis/local/bin:$PATH
        PYTHONPATH=$PYTHONPATH:$HOME/local/lib/python2.7/site-packages

  - os: linux
    compiler: clang
    env:
        PLATFORM=linux
        PATH=/home/travis/local/bin:$PATH
        PYTHONPATH=$PYTHONPATH:$HOME/local/lib/python2.7/site-packages
        QMAKESPEC=linux-clang

  allow_failures:
  - os: linux
    env:
        PLATFORM=rpi
        MNT=/home/travis/mnt

before_install: "if [ -f ./.travis/before_install.sh   ] ; then ./.travis/before_install.sh ; fi"
install:        "if [ -f ./.travis/install.sh          ] ; then ./.travis/install.sh        ; fi"
before_script:  "if [ -f ./.travis/before_script.sh    ] ; then ./.travis/before_script.sh  ; fi"
script:         "if [ -f ./.travis/script.sh           ] ; then ./.travis/script.sh         ; fi"
after_script:   "if [ -f ./.travis/after_script.sh     ] ; then ./.travis/after_script.sh   ; fi"

deploy:
  provider: releases
  api_key:
    secure: pXTKmYwykeSD1FSVFvkfR4q91X9AVkNPS2/FKDs+CnWDgFJyDrxsD8D596fLKA3OwbLD7QkXTBj4alhmj7OmcIf56ZZXlKy/O47OfC4JgHjkWYGIbE6CR/UpLRnGS251/zs8NjypnLSk+puiw1lHUqeIBqYGGCzkBN19uaGiyUc=
  file_glob: true
  file: propelleride-*
  skip_cleanup: true
  on:
    repo: parallaxinc/PropellerIDE
    tags: true
    all_branches: true
